name = "ju-sep-rank"
uuid = "d7d3a0ba-fdd8-4e96-9533-76425b4f269c"
authors = ["Andries <j.andries.j.steenkamp@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
